### ISSUE TITLE
Support the Classic IntelliMouse

### ISSUE THREAD

**Issue by madsl** [K-Visscher/intellimouse-ctl#3] opened 2020-05-20 13:17 UTC
I have a Classic Intellimouse at work I can test with, but due to covid I haven't been able to test your [gist](https://gist.github.com/K-Visscher/22561ca69a64339a7383d67db6e79818) with it yet. Will do it as soon as I can!

If it works, it would be neat if this control panel also could support the classic mouse :)

**Comment by K-Visscher** [comment] 2020-05-21 06:13
Yes, that would be great, from what I've seen from your captures over at the [libratbag issue](https://github.com/libratbag/libratbag/issues/537#issuecomment-424676479), they seem very similiar. 

If you would be so kind to make a capture of the Mouse and Keyboard Center starting up, while having your Classic IntelliMouse attached. That would help out a ton!
During the initital startup of the Mouse and Keyboard Center it reads all the current settings of the mouse, that would allow me to compare, if the way the settings are being read, are the same. 

Also please make note of the ranges of settings you're allowed to set, and take note of the settings before the startup, that should make sifting though the Wireshark capture a lot easier.

For now, from what I've seen the process for writing is precisely the same for both mice. (except they have different lengths for the payload and reports), so it should be totally doable.

**Comment by madsl** [comment] 2020-05-22 08:37
I went and picked up my Classic Mouse, and did another capture :)

When starting up Mouse and Keyboard center, the mouse was set to 800 dpi. Then I clicked the minus button so it went to 600 and then 400 (minimum). Then I pressed the plus button through all 200-increments up to 3200 dpi, and then back down again to 800 dpi. And then I closed Mouse and Keyboard center. Hope I got it right!

[classic_800-400-3200-800.pcapng.gz](https://github.com/K-Visscher/Pro-IntelliMouse-Control-Panel/files/4666957/classic_800-400-3200-800.pcapng.gz)

**Comment by madsl** [comment] 2020-05-22 08:38
You cannot set LED color with this mouse as far as I can see.

**Comment by madsl** [comment] 2020-05-22 08:58
I also added a comment on that libratbat [issue](https://github.com/libratbag/libratbag/issues/537#issuecomment-632581016), where I successfully tested your gist :)

**Comment by madsl** [comment] 2020-07-07 18:52
I'm looking at expanding the code supporting this - do you know what the correct __READ_REPORT_LENGTH_CLASSIC would be? And __POLLING_MAPPING_CLASSIC / __DISTANCE_MAPPING_CLASSIC? From your gist it seems like __WRITE_REPORT_LENGTH_CLASSIC should be 0x20.

**Comment by K-Visscher** [comment] 2020-07-10 20:14
Hi @madsl,

Yes, that's correct,  `__WRITE_REPORT_LENGTH_CLASSIC` is indeed `0x20`.
I think the correct `__READ_REPORT_LENGTH_CLASSIC` might be `0x07`. 
I haven't looked into the `__DISTANCE_MAPPING_CLASSIC` nor `__POLLING_MAPPING_CLASSIC` values yet nor their respective `PROPERTY_ID`'s. 
Is the lift off distance on the classic even configurable?

Also what would really help, is to create a capture where you only change the lift off distance / polling rate (and other configurable stuff) per capture, and change it back and forth between, some know values. Try to touch the mouse as little as possible, if at all. protip: if you're on a laptop, use the trackpad as it probably won't show up in the capture ;)

I think before we look into this further, we should first try to read from the device.

Could you please the script below:
```python
import hid
d = hid.device()
# TODO: change the path,  make sure you get interface 1
d.open_path(b'your_path_to_the_intellimouse_classic')

d.send_feature_report([0x24, 0x96, 0x03, 0x00, 0x20, 0x03] + [0x00] * 26)
d.send_feature_report([0x24, 0x97, 0x01] + [0x00] * 29)
result = d.get_input_report(0x27, 0x07)
print(int.from_bytes(result[4 : 4 + result[3]], byteorder='little'))


d.send_feature_report([0x24, 0x96, 0x03, 0x00, 0x40, 0x06] + [0x00] * 26)
d.send_feature_report([0x24, 0x97, 0x01] + [0x00] * 29)
result = d.get_input_report(0x27, 0x07)
print(int.from_bytes(result[4 : 4 + result[3]], byteorder='little'))
```

it should print out 800 and 1600.

**Comment by madsl** [comment] 2020-07-12 08:51
I'll pick up the mice from the office today :) And no, I don't think LOD is configurable on the classic...

**Comment by salty-horse** [comment] 2020-07-12 08:54
> I'll pick up the mice from the office today :) And no, I don't think LOD is configurable on the classic...

That's unfortunate. I was really hoping I could turn it off.

**Comment by madsl** [comment] 2020-07-12 11:25
![classic1](https://user-images.githubusercontent.com/426103/87245123-2a509b00-c443-11ea-8d96-bac886a98fa4.png)

**Comment by madsl** [comment] 2020-07-12 11:29
Hm, unfortunately, this is my output:

$ sudo python test.py 
0
0

**Comment by madsl** [comment] 2020-07-12 11:30
I ran it a few times:

$ sudo python test.py 
0
204800

$ sudo python test.py 
204800
0

$ sudo python test.py 
409600
409600

$ sudo python test.py 
0
204800

**Comment by K-Visscher** [comment] 2020-07-14 13:25
@salty-horse Lol, yes, I too prefer it when my mouse behaves more like a barcode scanner. such useful, many wow.

@madsl Okay, I get why it's fucking up the interpretation of the DPI, the mouse is doing some mixed endianness sourcery. Still doesn't explain why you sometimes get 0 or why both of them report back the same DPI.

Could you please try this again?

```python
import hid
d = hid.device()
# TODO: change the path,  make sure you get interface 1
# if there are multiple paths pointing to interface 1, please try them all.
d.open_path(b'your_path_to_the_intellimouse_classic')

d.send_feature_report([0x24, 0x96, 0x03, 0x00, 0x20, 0x03] + [0x00] * 26)
d.send_feature_report([0x24, 0x97, 0x01] + [0x00] * 29)
result = d.get_input_report(0x27, 0x07)
print(result)
print(int.from_bytes(result[-2], byteorder='little'))


d.send_feature_report([0x24, 0x96, 0x03, 0x00, 0x40, 0x06] + [0x00] * 26)
d.send_feature_report([0x24, 0x97, 0x01] + [0x00] * 29)
result = d.get_input_report(0x27, 0x07)
print(result)
print(int.from_bytes(result[-2:], byteorder='little'))
```

**Comment by madsl** [comment] 2020-07-15 21:40
```
$ sudo python test.py
[39, 151, 0, 3, 0, 64, 6]
1600
[39, 151, 0, 3, 0, 64, 6]
1600

$ sudo python test.py
[39, 151, 0, 3, 0, 64, 6]
1600
[39, 150, 0, 0, 0, 0, 0]
0

$ sudo python test.py
[39, 151, 0, 3, 0, 64, 6]
1600
[39, 151, 0, 3, 0, 64, 6]
1600

$ sudo python test.py
[39, 150, 0, 0, 0, 0, 0]
0
[39, 150, 0, 0, 0, 0, 0]
0
```

**Comment by madsl** [comment] 2021-12-20 23:19
Hi! Suggested this mouse for someone recently, and that made me think of this app again.

Do you think there's a possibility to add support for this mouse? :) Seems like they still sell a lot of it.

I guess I can help with the GUI part, but I'm not sure what should be there on the device control part of things.

**Comment by K-Visscher** [comment] 2022-01-14 15:40
Hi @madsl ,

I would certainly like to add it. 
It's just that having the physical device makes it a lot easier to tinker with, and it doesn't help that the test results above kinda bamboozle me.

There's a couple things we could still try to get this working:
* add a delay between writing/reading
* try using an `get_feature_report` instead of `get_input_report` as per this [pull-request](https://github.com/K-Visscher/pro-intellimouse-control-panel/pull/13)
* I could go over your captured data again and try to write a new test script, maybe I derped out somewhere :)

**Comment by K-Visscher** [comment] 2022-01-14 19:14
> I can sponsor you what you need to get hold of one? How much do you need?

You could buy one for me here:
https://www.amazon.nl/hz/wishlist/ls/1F3TOMTSV6UKV?ref_=wl_share

There is a used mouse for €21 (with minor aesthetic damage), new ones go for €27.95 including shipping/taxes.

I'd also be open to splitting it 50/50, since I have been wanting a smaller/lighter pro for a while.

If you don't want to make an Amazon account or want to work out details further you can contact me, via e-mail (check the `mail-to:` link on my website).

I promise that I'll work on it and try my best, but I can't give any guarantees beyond that.

**Comment by madsl** [comment] 2022-01-14 19:33
Order placed for a new one!

**Comment by K-Visscher** [comment] 2022-01-14 20:33
Thank you, very much!

**Comment by ernesto1** [comment] 2022-01-15 04:39
@madsl thanks for sponsoring the research of this project.  I just got the mouse myself and I must say we must get it supported on linux!  it is quite the piece of hardware

@K-Visscher if you require more people to test your development let me know

**Comment by madsl** [comment] 2022-01-23 14:58
@K-Visscher I sent you an email! Pretty sure it'll go to your spam folder, hence this message.

**Comment by K-Visscher** [comment] 2022-02-19 15:13
@ernesto1 
@madsl
I'm happy to inform you that I've added Classic IntelliMouse support.
Could you please help me out with testing and let me know what you think of it (and if it works for you), before I release it / merge with master?
```bash
git clone https://github.com/K-Visscher/pro-intellimouse-control-panel.git
git checkout classic-intellimouse-support
pip install .
sudo intellimouse-ctl list # e.g. 0. ProIntelliMouse @ "\\?\hid#vid_045e&pid_082a&mi_01&col05#8&309c5158&0&0004#{4d1e55b2-f16f-11cf-88cb-001111000030}"
sudo intellimouse-ctl get --dpi 0 # e.g. 800
sudo intellimouse-ctl set --dpi 1600 0
sudo intellimouse-ctl get --dpi 0 # e.g. 1600
```

**Comment by madsl** [comment] 2022-02-19 19:22
Nice!
```
$ sudo python3 -m intellimouse_ctl list
0. ClassicIntelliMouse @ "0001:0007:01"
$ sudo python3 -m intellimouse_ctl get --dpi 0
dpi: 0
$ sudo python3 -m intellimouse_ctl get --dpi 0
dpi: 1600
$ sudo python3 -m intellimouse_ctl set --dpi 800 0
$ sudo python3 -m intellimouse_ctl get --dpi 0
dpi: 800
$ sudo python3 -m intellimouse_ctl set --dpi 1600 0
$ sudo python3 -m intellimouse_ctl get --dpi 0
dpi: 1600
```

It seems to work! The only bug I could see was that the first time I wrote that get --dpi 0 command, it reported it as 0, but the second time it reported it correctly as 1600. Maybe there should be a retry a few times if it reads 0...

Great work!

**Comment by ernesto1** [comment] 2022-02-19 21:12
@K-Visscher of course, give me a bit and I'll try this out on my system

**Comment by ernesto1** [comment] 2022-02-19 21:34
My experience was similar to @madsl with the setup

```
ernesto@strike pro-intellimouse-control-panel]$ sudo intellimouse-ctl list
0. ClassicIntelliMouse @ "4-1:1.1"
[ernesto@strike pro-intellimouse-control-panel]$ sudo intellimouse-ctl get --dpi 0
dpi: 1600
[ernesto@strike pro-intellimouse-control-panel]$ sudo intellimouse-ctl set --dpi 1600 0
[ernesto@strike pro-intellimouse-control-panel]$ sudo intellimouse-ctl get --dpi 0
dpi: 0
[ernesto@strike pro-intellimouse-control-panel]$ sudo intellimouse-ctl get --dpi 0
dpi: 1600
```
The default setting is 1600 dpi, I bumped it to 3200 and know the mouse is flying :D

@K-Visscher , couple of questions for you
- can set the dpi to any random number in the range of 800 - 16000? 16000 being the max dpi on this mouse
- If I switch mouses do I have to run another command to disable this script?
- Do I have to run the `set dpi` command on boot?

**Comment by K-Visscher** [comment] 2022-02-20 16:49
@madsl Glad you're happy with it =^.^=

>  The only bug I could see was that the first time I wrote that get --dpi 0 command, it reported it as 0, but the second time it reported it correctly as 1600. Maybe there should be a retry a few times if it reads 0...

Mhh strange, I'll look into it further, if I can't find the cause I'll just run with your suggestion/workaround.

---
@ernesto1 

> * Can I set the dpi to any random number in the range of 800 - 16000? 16000 being the max dpi on this mouse.

I think you might be confused with the Pro IntelliMouse?
The Classic IntelliMouse has a range of 400 to 3200 with steps of 200.
The Pro IntelliMouse has a range of 200 to 16000 with steps of 50.

> * If I switch mouses do I have to run another command to disable this script?

Nope, the script is a one time thing (it doesn't run continously in the background or something like that), it quickly claims your mouse, writes some settings and then releases the mouse, all of this only happens when you decide to invoke it.
So it shouldn't interfere with other devices/mice.

> * Do I have to run the set dpi command on boot?

No, it should store the dpi settings persistently to the mouse' own memory (i.e. it remembers them).

---
Thank you both for testing so quickly!

**Comment by ernesto1** [comment] 2022-02-20 17:29
@K-Visscher thanks for clarifying things. If you need help testing your mice software in the future, feel free to reach out.

I noticed you use Qt toolit for the UI of the settings window.  As a gnome devotee, I would like to build a UI for this based on gnomes native GTK toolkit.  Can I trouble you in the future with questions once I am ready to build this?

**Comment by K-Visscher** [comment] 2022-02-20 19:12
@ernesto1 will do and sure ask away :)

**Comment by K-Visscher** [comment] 2022-02-21 12:49
@ernesto1 
@madsl
I think I might have fixed the issue with reading 0 for a given setting.
Could you please do:
```
git pull
pip uninstall intellimouse-ctl
pip install intellimouse-ctl
sudo python3
```
then paste the following snippet:
```python
from intellimouse import ClassicIntelliMouse

with ClassicIntelliMouse.enumerate()[0] as device:
    count = 0
    for i in range(1000):
        result = device.get_dpi()
        if result == 0:
            count += 1
    print(count)
 ``` 
and let me know what it prints?
(it might take some time tho)

**Comment by ernesto1** [comment] 2022-02-21 14:35
@K-Visscher i had trouble with these installation instructions
i'm assuming I should run the git pull from the same branch as yesterday

```
$ sudo pip uninstall intellimouse-ctl
Uninstalling intellimouse-ctl-1.0.0:
  Would remove:
    /usr/local/bin/intellimouse-ctl
    /usr/local/lib/python3.8/site-packages/intellimouse/*
    /usr/local/lib/python3.8/site-packages/intellimouse_ctl-1.0.0.dist-info/*
    /usr/local/lib/python3.8/site-packages/intellimouse_ctl/*
Proceed (y/n)? y
  Successfully uninstalled intellimouse-ctl-1.0.0

$ sudo pip install intellimouse-ctl
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip install --user` instead.
ERROR: Could not find a version that satisfies the requirement intellimouse-ctl (from versions: none)
ERROR: No matching distribution found for intellimouse-ctl

$ pip install --user intellimouse-ctl
ERROR: Could not find a version that satisfies the requirement intellimouse-ctl (from versions: none)
ERROR: No matching distribution found for intellimouse-ctl
```

**Comment by madsl** [comment] 2022-02-21 14:53
Nice!

```
In [1]: from intellimouse import ClassicIntelliMouse

In [2]: with ClassicIntelliMouse.enumerate()[0] as device:
   ...:     count = 0
   ...:     for i in range(1000):
   ...:         result = device.get_dpi()
   ...:         if result == 0:
   ...:             count += 1
   ...:     print(count)
0
```

**Comment by K-Visscher** [comment] 2022-02-21 15:52
@ernesto1 
> @K-Visscher i had trouble with these installation instructions i'm assuming I should run the git pull from the same branch as yesterday

Yeah `intellimouse-ctl` isn't a package on PyPI just yet, but it is going to be.
just `cd` into the repo and then `pip install .`  
And your assumption is correct you should be on the `classic-intellimouse-support` branch.

**Comment by ernesto1** [comment] 2022-02-21 17:26
@K-Visscher test passed, count was 0 as well :D

**Comment by K-Visscher** [comment] 2022-02-22 18:47
@ernesto1 there's a an demo GIF that i've made, it should help you figure things out.
If that isn't enough:
* `intellimouse-ctl --help`
* `intellimouse-ctl get --help`
* `intellimouse-ctl set --help`
Should help.

You can't really pass wrong info the device if a device doesn't support something, the arguments passed to it are ignored.
If the settings are invalid it wil raise an exception. Hope that clears it up for you :)

**Comment by K-Visscher** [comment] 2022-02-22 18:47
Closing this since it is now merged with main and a PyPi package is online :)

**Closed by K-Visscher** 2022-02-22 18:47 UTC
Labels: enhancement

**Comment by madsl** [comment] 2022-02-22 22:46
Thank you for your great work! Worked nicely
